### PR TITLE
Update group_humann2_uniref_abundances_to_go wrapper

### PR DESCRIPTION
**Pull request by jraysajulga**
Removes the tool_dependencies.xml file and updates versioning.

### CODE REVIEW

**Comment by jraysajulga** [comment]
Need to wait for an update to the Conda recipe.

**Comment by jraysajulga** [comment]
@bebatut I've updated the Conda recipe and it seems to be working now. Is this repo linked to the toolshed?

**Comment by jraysajulga** [comment]
@bebatut Björn has taken a look at the wrapper and I have implemented his suggestions. Can you take a look at it?

**Comment by bebatut** [comment]
Thanks a lot @jraysajulga!
I updated the bioconda package to use the latest release, once it is green I will merge it

**Comment by jraysajulga** [comment]
@bebatut No problem. Thank you!

**Comment by jraysajulga** [comment]
@bebatut Bioconda package is updated to the latest release (v1.3.0)!

**Comment by jraysajulga** [comment]
@bebatut Is this newer version available on the toolshed?

**Comment by bebatut** [comment]
@jraysajulga I made the update just now (I thought planemo will do it but no 😟 so I did it manually)

**Comment by jraysajulga** [comment]
Thanks!

**Pull request merged**
