### PR TITLE
Move tools to bgruening repository

### PR DESCRIPTION
**Pull request by gallardoalba**
Only the tools currently installed in the European server have been migrated. Part of https://github.com/bgruening/galaxytools/pull/1248

### CODE REVIEW

**Comment by bebatut** [comment]
Thanks a lot!!!

**Comment by bebatut** [comment]
@gallardoalba can you resolve the conflict there?  and then I can merge it :) Thanks a lot

**Comment by gallardoalba** [comment]
> `tools/format_cd_hit_output/format_cd_hit_output.xml`

I think the conflicts are caused because some tools have been removed, but I'm not sure.

**Comment by gallardoalba** [comment]
Should I close that PR?

**Pull request closed without merging**
