### PR TITLE
cdhit[-est][-2d] tool

### PR DESCRIPTION
**Pull request by bernt-matthias**
Based in the original tools a single tool that can call cd-hit, cd-hit-est, cd-hit-2d, cd-hit-est-2d has been implemented. 

There are some todos left and tests are necessary. But its a start. Would be happy to get some comments before I continue.

### CODE REVIEW

**Comment by bebatut** [comment]
Thanks @bernt-matthias 
Looks like a good start... 
We are thinking about moving it to IUC and merge with the @jj-umn version

**Comment by bernt-matthias** [comment]
Sounds great - lets join forces :)  Do you have a link for the repository?

One question: is the optional flag of the <param> tags useful if a default value is specified?

**Comment by bernt-matthias** [comment]
Nearly there.. 

An upstream problem seems to fail one of my tests: https://github.com/weizhongli/cdhit/issues/57

**Comment by bernt-matthias** [comment]
closed https://github.com/galaxyproject/tools-iuc/pull/1778

**Pull request closed without merging**
